/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const NoteColor = IDL.Variant({
  'blue' : IDL.Null,
  'pink' : IDL.Null,
  'purple' : IDL.Null,
  'green' : IDL.Null,
  'yellow' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ActiveTimerState = IDL.Record({
  'startTime' : IDL.Int,
  'pausedAt' : IDL.Opt(IDL.Int),
  'userId' : IDL.Principal,
  'isPaused' : IDL.Bool,
  'side' : IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null }),
  'totalPausedDuration' : IDL.Int,
  'childId' : IDL.Text,
});
export const TummyTimeTimerState = IDL.Record({
  'startTime' : IDL.Int,
  'pausedAt' : IDL.Opt(IDL.Int),
  'userId' : IDL.Principal,
  'isPaused' : IDL.Bool,
  'totalPausedDuration' : IDL.Int,
  'childId' : IDL.Text,
});
export const ChildProfileView = IDL.Record({
  'id' : IDL.Text,
  'birthDate' : IDL.Int,
  'name' : IDL.Text,
  'sharedWith' : IDL.Vec(IDL.Principal),
  'isPublic' : IDL.Bool,
  'photo' : IDL.Opt(ExternalBlob),
  'parent' : IDL.Principal,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const BreastfeedingSession = IDL.Record({
  'startTime' : IDL.Int,
  'duration' : IDL.Int,
  'side' : IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null }),
  'childId' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DiaperLog = IDL.Record({
  'contents' : IDL.Record({
    'tuscia' : IDL.Bool,
    'kakis' : IDL.Bool,
    'sysius' : IDL.Bool,
  }),
  'childId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const FeedingSession = IDL.Record({
  'color' : IDL.Text,
  'feedingType' : IDL.Variant({
    'misinukas' : IDL.Null,
    'mamosPienas' : IDL.Null,
  }),
  'childId' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'mlAmount' : IDL.Float64,
});
export const HeightEntry = IDL.Record({
  'height' : IDL.Float64,
  'heightId' : IDL.Text,
  'childId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const JournalNote = IDL.Record({
  'createdAt' : IDL.Int,
  'color' : NoteColor,
  'text' : IDL.Text,
  'childId' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const MilkPumpingSession = IDL.Record({
  'side' : IDL.Variant({
    'both' : IDL.Null,
    'left' : IDL.Null,
    'right' : IDL.Null,
  }),
  'childId' : IDL.Text,
  'timestamp' : IDL.Int,
  'sessionId' : IDL.Text,
  'mlAmount' : IDL.Float64,
});
export const SolidFoodEntry = IDL.Record({
  'color' : IDL.Text,
  'childId' : IDL.Text,
  'entryId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'category' : IDL.Variant({
    'grains' : IDL.Null,
    'berries' : IDL.Null,
    'eggs' : IDL.Null,
    'fish' : IDL.Null,
    'meat' : IDL.Null,
    'fruits' : IDL.Null,
    'vegetables' : IDL.Null,
  }),
  'reaction' : IDL.Variant({
    'unclear' : IDL.Null,
    'liked' : IDL.Null,
    'disliked' : IDL.Null,
  }),
  'foodName' : IDL.Text,
});
export const TummyTimeSession = IDL.Record({
  'startTime' : IDL.Int,
  'duration' : IDL.Int,
  'childId' : IDL.Text,
  'sessionId' : IDL.Text,
});
export const WeightEntry = IDL.Record({
  'weight' : IDL.Float64,
  'childId' : IDL.Text,
  'weightId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ImportCounts = IDL.Record({
  'feedingSessions' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'solidFoodEntries' : IDL.Record({
    'skipped' : IDL.Nat,
    'restored' : IDL.Nat,
  }),
  'heightEntries' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'weightEntries' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'activeTimers' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'userProfiles' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'tummyTimeSessions' : IDL.Record({
    'skipped' : IDL.Nat,
    'restored' : IDL.Nat,
  }),
  'journalNotes' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'diaperLogs' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'tummyTimeTimers' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'breastfeedingSessions' : IDL.Record({
    'skipped' : IDL.Nat,
    'restored' : IDL.Nat,
  }),
  'childInviteLinks' : IDL.Record({
    'skipped' : IDL.Nat,
    'restored' : IDL.Nat,
  }),
  'childProfiles' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
  'milkPumpingSessions' : IDL.Record({
    'skipped' : IDL.Nat,
    'restored' : IDL.Nat,
  }),
});
export const ImportResult = IDL.Record({
  'totalRestored' : IDL.Nat,
  'success' : IDL.Bool,
  'counts' : ImportCounts,
  'totalSkipped' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptChildInvite' : IDL.Func([IDL.Text], [], []),
  'addChild' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Opt(ExternalBlob), IDL.Bool],
      [IDL.Text],
      [],
    ),
  'addFeedingSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        IDL.Variant({ 'misinukas' : IDL.Null, 'mamosPienas' : IDL.Null }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'addHeightEntry' : IDL.Func([IDL.Text, IDL.Float64, IDL.Int], [], []),
  'addJournalNote' : IDL.Func([IDL.Text, IDL.Text, NoteColor], [], []),
  'addManualBreastfeedingSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Int,
        IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null }),
      ],
      [],
      [],
    ),
  'addMilkPumpingSession' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Float64,
        IDL.Variant({
          'both' : IDL.Null,
          'left' : IDL.Null,
          'right' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'addSolidFoodEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'grains' : IDL.Null,
          'berries' : IDL.Null,
          'eggs' : IDL.Null,
          'fish' : IDL.Null,
          'meat' : IDL.Null,
          'fruits' : IDL.Null,
          'vegetables' : IDL.Null,
        }),
        IDL.Text,
        IDL.Variant({
          'unclear' : IDL.Null,
          'liked' : IDL.Null,
          'disliked' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
        IDL.Int,
      ],
      [],
      [],
    ),
  'addWeightEntry' : IDL.Func([IDL.Text, IDL.Float64, IDL.Int], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateAgeInDays' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'completeBreastfeedingSession' : IDL.Func([IDL.Text], [], []),
  'completeTummyTimeSession' : IDL.Func([IDL.Text], [], []),
  'deleteFeedingSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteHeightEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteJournalNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMilkPumpingSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteSolidFoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteTummyTimeSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteWeightEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'exportAllData' : IDL.Func([], [IDL.Text], ['query']),
  'generateChildInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getActiveBreastfeedingTimer' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ActiveTimerState)],
      ['query'],
    ),
  'getActiveTummyTimeTimer' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TummyTimeTimerState)],
      ['query'],
    ),
  'getAllPublicChildren' : IDL.Func([], [IDL.Vec(ChildProfileView)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getBreastfeedingSessionsForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BreastfeedingSession)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChild' : IDL.Func([IDL.Text], [ChildProfileView], ['query']),
  'getChildStatistics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalDiapers' : IDL.Nat,
          'totalBreastfeedingSessions' : IDL.Nat,
          'totalTummyTime' : IDL.Int,
        }),
      ],
      ['query'],
    ),
  'getChildrenByParent' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ChildProfileView)],
      ['query'],
    ),
  'getDiaperLogsForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DiaperLog)],
      ['query'],
    ),
  'getFeedingSessionsForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FeedingSession)],
      ['query'],
    ),
  'getHeightEntriesForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HeightEntry)],
      ['query'],
    ),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getJournalNotesForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JournalNote)],
      ['query'],
    ),
  'getMilkPumpingSessionsForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MilkPumpingSession)],
      ['query'],
    ),
  'getSharedChildren' : IDL.Func([], [IDL.Vec(ChildProfileView)], ['query']),
  'getSharedUsers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getSolidFoodEntriesForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SolidFoodEntry)],
      ['query'],
    ),
  'getSolidFoodStatistics' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'thisWeek' : IDL.Nat,
          'thisYear' : IDL.Nat,
          'thisMonth' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSolidFoodStatisticsByCategory' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Int],
      [
        IDL.Record({
          'grains' : IDL.Nat,
          'berries' : IDL.Nat,
          'eggs' : IDL.Nat,
          'fish' : IDL.Nat,
          'meat' : IDL.Nat,
          'fruits' : IDL.Nat,
          'vegetables' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTummyTimeSessionsForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TummyTimeSession)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeightEntriesForChild' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WeightEntry)],
      ['query'],
    ),
  'importAllData' : IDL.Func([IDL.Text], [ImportResult], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logDiaperChange' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'pauseBreastfeedingTimer' : IDL.Func([IDL.Text], [], []),
  'pauseTummyTimeTimer' : IDL.Func([IDL.Text], [], []),
  'regenerateChildPhoto' : IDL.Func([IDL.Text], [], []),
  'resumeBreastfeedingTimer' : IDL.Func([IDL.Text], [], []),
  'resumeTummyTimeTimer' : IDL.Func([IDL.Text], [], []),
  'revokeChildAccess' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchJournalNotes' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(JournalNote)],
      ['query'],
    ),
  'shareChildWithUser' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'startBreastfeedingSession' : IDL.Func(
      [IDL.Text, IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null })],
      [],
      [],
    ),
  'startTummyTimeSession' : IDL.Func([IDL.Text], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'toggleChildVisibility' : IDL.Func([IDL.Text], [], []),
  'updateHeightEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Int],
      [],
      [],
    ),
  'updateJournalNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(NoteColor)],
      [],
      [],
    ),
  'updateSolidFoodEntry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({
          'grains' : IDL.Null,
          'berries' : IDL.Null,
          'eggs' : IDL.Null,
          'fish' : IDL.Null,
          'meat' : IDL.Null,
          'fruits' : IDL.Null,
          'vegetables' : IDL.Null,
        }),
        IDL.Text,
        IDL.Variant({
          'unclear' : IDL.Null,
          'liked' : IDL.Null,
          'disliked' : IDL.Null,
        }),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'updateWeightEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const NoteColor = IDL.Variant({
    'blue' : IDL.Null,
    'pink' : IDL.Null,
    'purple' : IDL.Null,
    'green' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ActiveTimerState = IDL.Record({
    'startTime' : IDL.Int,
    'pausedAt' : IDL.Opt(IDL.Int),
    'userId' : IDL.Principal,
    'isPaused' : IDL.Bool,
    'side' : IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null }),
    'totalPausedDuration' : IDL.Int,
    'childId' : IDL.Text,
  });
  const TummyTimeTimerState = IDL.Record({
    'startTime' : IDL.Int,
    'pausedAt' : IDL.Opt(IDL.Int),
    'userId' : IDL.Principal,
    'isPaused' : IDL.Bool,
    'totalPausedDuration' : IDL.Int,
    'childId' : IDL.Text,
  });
  const ChildProfileView = IDL.Record({
    'id' : IDL.Text,
    'birthDate' : IDL.Int,
    'name' : IDL.Text,
    'sharedWith' : IDL.Vec(IDL.Principal),
    'isPublic' : IDL.Bool,
    'photo' : IDL.Opt(ExternalBlob),
    'parent' : IDL.Principal,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const BreastfeedingSession = IDL.Record({
    'startTime' : IDL.Int,
    'duration' : IDL.Int,
    'side' : IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null }),
    'childId' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DiaperLog = IDL.Record({
    'contents' : IDL.Record({
      'tuscia' : IDL.Bool,
      'kakis' : IDL.Bool,
      'sysius' : IDL.Bool,
    }),
    'childId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const FeedingSession = IDL.Record({
    'color' : IDL.Text,
    'feedingType' : IDL.Variant({
      'misinukas' : IDL.Null,
      'mamosPienas' : IDL.Null,
    }),
    'childId' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'mlAmount' : IDL.Float64,
  });
  const HeightEntry = IDL.Record({
    'height' : IDL.Float64,
    'heightId' : IDL.Text,
    'childId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const JournalNote = IDL.Record({
    'createdAt' : IDL.Int,
    'color' : NoteColor,
    'text' : IDL.Text,
    'childId' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const MilkPumpingSession = IDL.Record({
    'side' : IDL.Variant({
      'both' : IDL.Null,
      'left' : IDL.Null,
      'right' : IDL.Null,
    }),
    'childId' : IDL.Text,
    'timestamp' : IDL.Int,
    'sessionId' : IDL.Text,
    'mlAmount' : IDL.Float64,
  });
  const SolidFoodEntry = IDL.Record({
    'color' : IDL.Text,
    'childId' : IDL.Text,
    'entryId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'category' : IDL.Variant({
      'grains' : IDL.Null,
      'berries' : IDL.Null,
      'eggs' : IDL.Null,
      'fish' : IDL.Null,
      'meat' : IDL.Null,
      'fruits' : IDL.Null,
      'vegetables' : IDL.Null,
    }),
    'reaction' : IDL.Variant({
      'unclear' : IDL.Null,
      'liked' : IDL.Null,
      'disliked' : IDL.Null,
    }),
    'foodName' : IDL.Text,
  });
  const TummyTimeSession = IDL.Record({
    'startTime' : IDL.Int,
    'duration' : IDL.Int,
    'childId' : IDL.Text,
    'sessionId' : IDL.Text,
  });
  const WeightEntry = IDL.Record({
    'weight' : IDL.Float64,
    'childId' : IDL.Text,
    'weightId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ImportCounts = IDL.Record({
    'feedingSessions' : IDL.Record({
      'skipped' : IDL.Nat,
      'restored' : IDL.Nat,
    }),
    'solidFoodEntries' : IDL.Record({
      'skipped' : IDL.Nat,
      'restored' : IDL.Nat,
    }),
    'heightEntries' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
    'weightEntries' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
    'activeTimers' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
    'userProfiles' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
    'tummyTimeSessions' : IDL.Record({
      'skipped' : IDL.Nat,
      'restored' : IDL.Nat,
    }),
    'journalNotes' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
    'diaperLogs' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
    'tummyTimeTimers' : IDL.Record({
      'skipped' : IDL.Nat,
      'restored' : IDL.Nat,
    }),
    'breastfeedingSessions' : IDL.Record({
      'skipped' : IDL.Nat,
      'restored' : IDL.Nat,
    }),
    'childInviteLinks' : IDL.Record({
      'skipped' : IDL.Nat,
      'restored' : IDL.Nat,
    }),
    'childProfiles' : IDL.Record({ 'skipped' : IDL.Nat, 'restored' : IDL.Nat }),
    'milkPumpingSessions' : IDL.Record({
      'skipped' : IDL.Nat,
      'restored' : IDL.Nat,
    }),
  });
  const ImportResult = IDL.Record({
    'totalRestored' : IDL.Nat,
    'success' : IDL.Bool,
    'counts' : ImportCounts,
    'totalSkipped' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptChildInvite' : IDL.Func([IDL.Text], [], []),
    'addChild' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Opt(ExternalBlob), IDL.Bool],
        [IDL.Text],
        [],
      ),
    'addFeedingSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          IDL.Variant({ 'misinukas' : IDL.Null, 'mamosPienas' : IDL.Null }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'addHeightEntry' : IDL.Func([IDL.Text, IDL.Float64, IDL.Int], [], []),
    'addJournalNote' : IDL.Func([IDL.Text, IDL.Text, NoteColor], [], []),
    'addManualBreastfeedingSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Int,
          IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null }),
        ],
        [],
        [],
      ),
    'addMilkPumpingSession' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Float64,
          IDL.Variant({
            'both' : IDL.Null,
            'left' : IDL.Null,
            'right' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'addSolidFoodEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'grains' : IDL.Null,
            'berries' : IDL.Null,
            'eggs' : IDL.Null,
            'fish' : IDL.Null,
            'meat' : IDL.Null,
            'fruits' : IDL.Null,
            'vegetables' : IDL.Null,
          }),
          IDL.Text,
          IDL.Variant({
            'unclear' : IDL.Null,
            'liked' : IDL.Null,
            'disliked' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
          IDL.Int,
        ],
        [],
        [],
      ),
    'addWeightEntry' : IDL.Func([IDL.Text, IDL.Float64, IDL.Int], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateAgeInDays' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'completeBreastfeedingSession' : IDL.Func([IDL.Text], [], []),
    'completeTummyTimeSession' : IDL.Func([IDL.Text], [], []),
    'deleteFeedingSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteHeightEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteJournalNote' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMilkPumpingSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteSolidFoodEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteTummyTimeSession' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteWeightEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'exportAllData' : IDL.Func([], [IDL.Text], ['query']),
    'generateChildInviteLink' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getActiveBreastfeedingTimer' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ActiveTimerState)],
        ['query'],
      ),
    'getActiveTummyTimeTimer' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TummyTimeTimerState)],
        ['query'],
      ),
    'getAllPublicChildren' : IDL.Func(
        [],
        [IDL.Vec(ChildProfileView)],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getBreastfeedingSessionsForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BreastfeedingSession)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChild' : IDL.Func([IDL.Text], [ChildProfileView], ['query']),
    'getChildStatistics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalDiapers' : IDL.Nat,
            'totalBreastfeedingSessions' : IDL.Nat,
            'totalTummyTime' : IDL.Int,
          }),
        ],
        ['query'],
      ),
    'getChildrenByParent' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ChildProfileView)],
        ['query'],
      ),
    'getDiaperLogsForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DiaperLog)],
        ['query'],
      ),
    'getFeedingSessionsForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FeedingSession)],
        ['query'],
      ),
    'getHeightEntriesForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HeightEntry)],
        ['query'],
      ),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getJournalNotesForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JournalNote)],
        ['query'],
      ),
    'getMilkPumpingSessionsForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MilkPumpingSession)],
        ['query'],
      ),
    'getSharedChildren' : IDL.Func([], [IDL.Vec(ChildProfileView)], ['query']),
    'getSharedUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getSolidFoodEntriesForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SolidFoodEntry)],
        ['query'],
      ),
    'getSolidFoodStatistics' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'thisWeek' : IDL.Nat,
            'thisYear' : IDL.Nat,
            'thisMonth' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSolidFoodStatisticsByCategory' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Int],
        [
          IDL.Record({
            'grains' : IDL.Nat,
            'berries' : IDL.Nat,
            'eggs' : IDL.Nat,
            'fish' : IDL.Nat,
            'meat' : IDL.Nat,
            'fruits' : IDL.Nat,
            'vegetables' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTummyTimeSessionsForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TummyTimeSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeightEntriesForChild' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WeightEntry)],
        ['query'],
      ),
    'importAllData' : IDL.Func([IDL.Text], [ImportResult], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logDiaperChange' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'pauseBreastfeedingTimer' : IDL.Func([IDL.Text], [], []),
    'pauseTummyTimeTimer' : IDL.Func([IDL.Text], [], []),
    'regenerateChildPhoto' : IDL.Func([IDL.Text], [], []),
    'resumeBreastfeedingTimer' : IDL.Func([IDL.Text], [], []),
    'resumeTummyTimeTimer' : IDL.Func([IDL.Text], [], []),
    'revokeChildAccess' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchJournalNotes' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(JournalNote)],
        ['query'],
      ),
    'shareChildWithUser' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'startBreastfeedingSession' : IDL.Func(
        [IDL.Text, IDL.Variant({ 'left' : IDL.Null, 'right' : IDL.Null })],
        [],
        [],
      ),
    'startTummyTimeSession' : IDL.Func([IDL.Text], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'toggleChildVisibility' : IDL.Func([IDL.Text], [], []),
    'updateHeightEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Int],
        [],
        [],
      ),
    'updateJournalNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(NoteColor)],
        [],
        [],
      ),
    'updateSolidFoodEntry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({
            'grains' : IDL.Null,
            'berries' : IDL.Null,
            'eggs' : IDL.Null,
            'fish' : IDL.Null,
            'meat' : IDL.Null,
            'fruits' : IDL.Null,
            'vegetables' : IDL.Null,
          }),
          IDL.Text,
          IDL.Variant({
            'unclear' : IDL.Null,
            'liked' : IDL.Null,
            'disliked' : IDL.Null,
          }),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'updateWeightEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };