/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActiveTimerState {
  'startTime' : bigint,
  'pausedAt' : [] | [bigint],
  'userId' : Principal,
  'isPaused' : boolean,
  'side' : { 'left' : null } |
    { 'right' : null },
  'totalPausedDuration' : bigint,
  'childId' : string,
}
export interface BreastfeedingSession {
  'startTime' : bigint,
  'duration' : bigint,
  'side' : { 'left' : null } |
    { 'right' : null },
  'childId' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface ChildProfileView {
  'id' : string,
  'birthDate' : bigint,
  'name' : string,
  'sharedWith' : Array<Principal>,
  'isPublic' : boolean,
  'photo' : [] | [ExternalBlob],
  'parent' : Principal,
}
export interface DiaperLog {
  'contents' : { 'tuscia' : boolean, 'kakis' : boolean, 'sysius' : boolean },
  'childId' : string,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FeedingSession {
  'color' : string,
  'feedingType' : { 'misinukas' : null } |
    { 'mamosPienas' : null },
  'childId' : string,
  'timestamp' : bigint,
  'sessionId' : string,
  'mlAmount' : number,
}
export interface HeightEntry {
  'height' : number,
  'heightId' : string,
  'childId' : string,
  'timestamp' : bigint,
}
export interface ImportCounts {
  'feedingSessions' : { 'skipped' : bigint, 'restored' : bigint },
  'solidFoodEntries' : { 'skipped' : bigint, 'restored' : bigint },
  'heightEntries' : { 'skipped' : bigint, 'restored' : bigint },
  'weightEntries' : { 'skipped' : bigint, 'restored' : bigint },
  'activeTimers' : { 'skipped' : bigint, 'restored' : bigint },
  'userProfiles' : { 'skipped' : bigint, 'restored' : bigint },
  'tummyTimeSessions' : { 'skipped' : bigint, 'restored' : bigint },
  'journalNotes' : { 'skipped' : bigint, 'restored' : bigint },
  'diaperLogs' : { 'skipped' : bigint, 'restored' : bigint },
  'tummyTimeTimers' : { 'skipped' : bigint, 'restored' : bigint },
  'breastfeedingSessions' : { 'skipped' : bigint, 'restored' : bigint },
  'childInviteLinks' : { 'skipped' : bigint, 'restored' : bigint },
  'childProfiles' : { 'skipped' : bigint, 'restored' : bigint },
  'milkPumpingSessions' : { 'skipped' : bigint, 'restored' : bigint },
}
export interface ImportResult {
  'totalRestored' : bigint,
  'success' : boolean,
  'counts' : ImportCounts,
  'totalSkipped' : bigint,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface JournalNote {
  'createdAt' : bigint,
  'color' : NoteColor,
  'text' : string,
  'childId' : string,
  'updatedAt' : bigint,
}
export interface MilkPumpingSession {
  'side' : { 'both' : null } |
    { 'left' : null } |
    { 'right' : null },
  'childId' : string,
  'timestamp' : bigint,
  'sessionId' : string,
  'mlAmount' : number,
}
export type NoteColor = { 'blue' : null } |
  { 'pink' : null } |
  { 'purple' : null } |
  { 'green' : null } |
  { 'yellow' : null };
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface SolidFoodEntry {
  'color' : string,
  'childId' : string,
  'entryId' : string,
  'notes' : [] | [string],
  'timestamp' : bigint,
  'category' : { 'grains' : null } |
    { 'berries' : null } |
    { 'eggs' : null } |
    { 'fish' : null } |
    { 'meat' : null } |
    { 'fruits' : null } |
    { 'vegetables' : null },
  'reaction' : { 'unclear' : null } |
    { 'liked' : null } |
    { 'disliked' : null },
  'foodName' : string,
}
export type Time = bigint;
export interface TummyTimeSession {
  'startTime' : bigint,
  'duration' : bigint,
  'childId' : string,
  'sessionId' : string,
}
export interface TummyTimeTimerState {
  'startTime' : bigint,
  'pausedAt' : [] | [bigint],
  'userId' : Principal,
  'isPaused' : boolean,
  'totalPausedDuration' : bigint,
  'childId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WeightEntry {
  'weight' : number,
  'childId' : string,
  'weightId' : string,
  'timestamp' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptChildInvite' : ActorMethod<[string], undefined>,
  'addChild' : ActorMethod<
    [string, bigint, [] | [ExternalBlob], boolean],
    string
  >,
  'addFeedingSession' : ActorMethod<
    [
      string,
      bigint,
      number,
      { 'misinukas' : null } |
        { 'mamosPienas' : null },
      string,
    ],
    undefined
  >,
  'addHeightEntry' : ActorMethod<[string, number, bigint], undefined>,
  'addJournalNote' : ActorMethod<[string, string, NoteColor], undefined>,
  'addManualBreastfeedingSession' : ActorMethod<
    [string, bigint, bigint, { 'left' : null } | { 'right' : null }],
    undefined
  >,
  'addMilkPumpingSession' : ActorMethod<
    [
      string,
      bigint,
      number,
      { 'both' : null } |
        { 'left' : null } |
        { 'right' : null },
    ],
    undefined
  >,
  'addSolidFoodEntry' : ActorMethod<
    [
      string,
      string,
      { 'grains' : null } |
        { 'berries' : null } |
        { 'eggs' : null } |
        { 'fish' : null } |
        { 'meat' : null } |
        { 'fruits' : null } |
        { 'vegetables' : null },
      string,
      { 'unclear' : null } |
        { 'liked' : null } |
        { 'disliked' : null },
      [] | [string],
      bigint,
    ],
    undefined
  >,
  'addWeightEntry' : ActorMethod<[string, number, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateAgeInDays' : ActorMethod<[string], bigint>,
  'completeBreastfeedingSession' : ActorMethod<[string], undefined>,
  'completeTummyTimeSession' : ActorMethod<[string], undefined>,
  'deleteFeedingSession' : ActorMethod<[string, string], undefined>,
  'deleteHeightEntry' : ActorMethod<[string, string], undefined>,
  'deleteJournalNote' : ActorMethod<[string, string], undefined>,
  'deleteMilkPumpingSession' : ActorMethod<[string, string], undefined>,
  'deleteSolidFoodEntry' : ActorMethod<[string, string], undefined>,
  'deleteTummyTimeSession' : ActorMethod<[string, string], undefined>,
  'deleteWeightEntry' : ActorMethod<[string, string], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'exportAllData' : ActorMethod<[], string>,
  'generateChildInviteLink' : ActorMethod<[string], string>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getActiveBreastfeedingTimer' : ActorMethod<
    [string],
    [] | [ActiveTimerState]
  >,
  'getActiveTummyTimeTimer' : ActorMethod<[string], [] | [TummyTimeTimerState]>,
  'getAllPublicChildren' : ActorMethod<[], Array<ChildProfileView>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getApiDoc' : ActorMethod<[], string>,
  'getBreastfeedingSessionsForChild' : ActorMethod<
    [string],
    Array<BreastfeedingSession>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChild' : ActorMethod<[string], ChildProfileView>,
  'getChildStatistics' : ActorMethod<
    [string],
    {
      'totalDiapers' : bigint,
      'totalBreastfeedingSessions' : bigint,
      'totalTummyTime' : bigint,
    }
  >,
  'getChildrenByParent' : ActorMethod<[Principal], Array<ChildProfileView>>,
  'getDiaperLogsForChild' : ActorMethod<[string], Array<DiaperLog>>,
  'getFeedingSessionsForChild' : ActorMethod<[string], Array<FeedingSession>>,
  'getHeightEntriesForChild' : ActorMethod<[string], Array<HeightEntry>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getJournalNotesForChild' : ActorMethod<[string], Array<JournalNote>>,
  'getMilkPumpingSessionsForChild' : ActorMethod<
    [string],
    Array<MilkPumpingSession>
  >,
  'getSharedChildren' : ActorMethod<[], Array<ChildProfileView>>,
  'getSharedUsers' : ActorMethod<[string], Array<Principal>>,
  'getSolidFoodEntriesForChild' : ActorMethod<[string], Array<SolidFoodEntry>>,
  'getSolidFoodStatistics' : ActorMethod<
    [string],
    { 'thisWeek' : bigint, 'thisYear' : bigint, 'thisMonth' : bigint }
  >,
  'getSolidFoodStatisticsByCategory' : ActorMethod<
    [string, bigint, bigint],
    {
      'grains' : bigint,
      'berries' : bigint,
      'eggs' : bigint,
      'fish' : bigint,
      'meat' : bigint,
      'fruits' : bigint,
      'vegetables' : bigint,
    }
  >,
  'getTummyTimeSessionsForChild' : ActorMethod<
    [string],
    Array<TummyTimeSession>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeightEntriesForChild' : ActorMethod<[string], Array<WeightEntry>>,
  'importAllData' : ActorMethod<[string], ImportResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logDiaperChange' : ActorMethod<
    [string, boolean, boolean, boolean],
    undefined
  >,
  'pauseBreastfeedingTimer' : ActorMethod<[string], undefined>,
  'pauseTummyTimeTimer' : ActorMethod<[string], undefined>,
  'regenerateChildPhoto' : ActorMethod<[string], undefined>,
  'resumeBreastfeedingTimer' : ActorMethod<[string], undefined>,
  'resumeTummyTimeTimer' : ActorMethod<[string], undefined>,
  'revokeChildAccess' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  'searchJournalNotes' : ActorMethod<[string, string], Array<JournalNote>>,
  'shareChildWithUser' : ActorMethod<[string, Principal], undefined>,
  'startBreastfeedingSession' : ActorMethod<
    [string, { 'left' : null } | { 'right' : null }],
    undefined
  >,
  'startTummyTimeSession' : ActorMethod<[string], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'toggleChildVisibility' : ActorMethod<[string], undefined>,
  'updateHeightEntry' : ActorMethod<
    [string, string, number, bigint],
    undefined
  >,
  'updateJournalNote' : ActorMethod<
    [string, string, string, [] | [NoteColor]],
    undefined
  >,
  'updateSolidFoodEntry' : ActorMethod<
    [
      string,
      string,
      string,
      { 'grains' : null } |
        { 'berries' : null } |
        { 'eggs' : null } |
        { 'fish' : null } |
        { 'meat' : null } |
        { 'fruits' : null } |
        { 'vegetables' : null },
      string,
      { 'unclear' : null } |
        { 'liked' : null } |
        { 'disliked' : null },
      [] | [string],
    ],
    undefined
  >,
  'updateWeightEntry' : ActorMethod<
    [string, string, number, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];