/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface SolidFoodEntry {
    color: string;
    childId: string;
    entryId: string;
    notes?: string;
    timestamp: bigint;
    category: Variant_grains_berries_eggs_fish_meat_fruits_vegetables;
    reaction: Variant_unclear_liked_disliked;
    foodName: string;
}
export interface HeightEntry {
    height: number;
    heightId: string;
    childId: string;
    timestamp: bigint;
}
export interface FeedingSession {
    color: string;
    feedingType: Variant_misinukas_mamosPienas;
    childId: string;
    timestamp: bigint;
    sessionId: string;
    mlAmount: number;
}
export type Time = bigint;
export interface TummyTimeSession {
    startTime: bigint;
    duration: bigint;
    childId: string;
    sessionId: string;
}
export interface TummyTimeTimerState {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    totalPausedDuration: bigint;
    childId: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DiaperLog {
    contents: {
        tuscia: boolean;
        kakis: boolean;
        sysius: boolean;
    };
    childId: string;
    timestamp: bigint;
}
export interface ChildProfileView {
    id: string;
    birthDate: bigint;
    name: string;
    sharedWith: Array<Principal>;
    isPublic: boolean;
    photo?: ExternalBlob;
    parent: Principal;
}
export interface JournalNote {
    createdAt: bigint;
    color: NoteColor;
    text: string;
    childId: string;
    updatedAt: bigint;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BreastfeedingSession {
    startTime: bigint;
    duration: bigint;
    side: Variant_left_right;
    childId: string;
}
export interface ActiveTimerState {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    side: Variant_left_right;
    totalPausedDuration: bigint;
    childId: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export interface WeightEntry {
    weight: number;
    childId: string;
    weightId: string;
    timestamp: bigint;
}
export interface UserProfile {
    name: string;
}
export interface MilkPumpingSession {
    side: Variant_both_left_right;
    childId: string;
    timestamp: bigint;
    sessionId: string;
    mlAmount: number;
}
export enum NoteColor {
    blue = "blue",
    pink = "pink",
    purple = "purple",
    green = "green",
    yellow = "yellow"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_both_left_right {
    both = "both",
    left = "left",
    right = "right"
}
export enum Variant_grains_berries_eggs_fish_meat_fruits_vegetables {
    grains = "grains",
    berries = "berries",
    eggs = "eggs",
    fish = "fish",
    meat = "meat",
    fruits = "fruits",
    vegetables = "vegetables"
}
export enum Variant_left_right {
    left = "left",
    right = "right"
}
export enum Variant_misinukas_mamosPienas {
    misinukas = "misinukas",
    mamosPienas = "mamosPienas"
}
export enum Variant_unclear_liked_disliked {
    unclear = "unclear",
    liked = "liked",
    disliked = "disliked"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptChildInvite(inviteCode: string): Promise<void>;
    addChild(name: string, birthDate: bigint, photo: ExternalBlob | null, isPublic: boolean): Promise<string>;
    addFeedingSession(childId: string, timestamp: bigint, mlAmount: number, feedingType: Variant_misinukas_mamosPienas, color: string): Promise<void>;
    addHeightEntry(childId: string, heightCm: number, dateTimestamp: bigint): Promise<void>;
    addJournalNote(childId: string, text: string, color: NoteColor): Promise<void>;
    addManualBreastfeedingSession(childId: string, date: bigint, duration: bigint, side: Variant_left_right): Promise<void>;
    addMilkPumpingSession(childId: string, timestamp: bigint, mlAmount: number, side: Variant_both_left_right): Promise<void>;
    addSolidFoodEntry(childId: string, foodName: string, category: Variant_grains_berries_eggs_fish_meat_fruits_vegetables, color: string, reaction: Variant_unclear_liked_disliked, notes: string | null, timestamp: bigint): Promise<void>;
    addWeightEntry(childId: string, weight: number, timestamp: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateAgeInDays(childId: string): Promise<bigint>;
    completeBreastfeedingSession(childId: string): Promise<void>;
    completeTummyTimeSession(childId: string): Promise<void>;
    deleteFeedingSession(childId: string, sessionId: string): Promise<void>;
    deleteHeightEntry(childId: string, heightId: string): Promise<void>;
    deleteJournalNote(childId: string, noteId: string): Promise<void>;
    deleteMilkPumpingSession(childId: string, sessionId: string): Promise<void>;
    deleteSolidFoodEntry(childId: string, entryId: string): Promise<void>;
    deleteTummyTimeSession(childId: string, sessionId: string): Promise<void>;
    deleteWeightEntry(childId: string, weightId: string): Promise<void>;
    execute(qJson: string): Promise<Result>;
    generateChildInviteLink(childId: string): Promise<string>;
    generateInviteCode(): Promise<string>;
    getActiveBreastfeedingTimer(childId: string): Promise<ActiveTimerState | null>;
    getActiveTummyTimeTimer(childId: string): Promise<TummyTimeTimerState | null>;
    getAllPublicChildren(): Promise<Array<ChildProfileView>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getBreastfeedingSessionsForChild(childId: string): Promise<Array<BreastfeedingSession>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChild(childId: string): Promise<ChildProfileView>;
    getChildStatistics(childId: string): Promise<{
        totalDiapers: bigint;
        totalBreastfeedingSessions: bigint;
        totalTummyTime: bigint;
    }>;
    getChildrenByParent(parent: Principal): Promise<Array<ChildProfileView>>;
    getDiaperLogsForChild(childId: string): Promise<Array<DiaperLog>>;
    getFeedingSessionsForChild(childId: string): Promise<Array<FeedingSession>>;
    getHeightEntriesForChild(childId: string): Promise<Array<HeightEntry>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getJournalNotesForChild(childId: string): Promise<Array<JournalNote>>;
    getMilkPumpingSessionsForChild(childId: string): Promise<Array<MilkPumpingSession>>;
    getSharedChildren(): Promise<Array<ChildProfileView>>;
    getSharedUsers(childId: string): Promise<Array<Principal>>;
    getSolidFoodEntriesForChild(childId: string): Promise<Array<SolidFoodEntry>>;
    getSolidFoodStatistics(childId: string): Promise<{
        thisWeek: bigint;
        thisYear: bigint;
        thisMonth: bigint;
    }>;
    getSolidFoodStatisticsByCategory(childId: string, startDate: bigint, endDate: bigint): Promise<{
        grains: bigint;
        berries: bigint;
        eggs: bigint;
        fish: bigint;
        meat: bigint;
        fruits: bigint;
        vegetables: bigint;
    }>;
    getTummyTimeSessionsForChild(childId: string): Promise<Array<TummyTimeSession>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWeightEntriesForChild(childId: string): Promise<Array<WeightEntry>>;
    isCallerAdmin(): Promise<boolean>;
    logDiaperChange(childId: string, kakis: boolean, sysius: boolean, tuscia: boolean): Promise<void>;
    pauseBreastfeedingTimer(childId: string): Promise<void>;
    pauseTummyTimeTimer(childId: string): Promise<void>;
    regenerateChildPhoto(childId: string): Promise<void>;
    resumeBreastfeedingTimer(childId: string): Promise<void>;
    resumeTummyTimeTimer(childId: string): Promise<void>;
    revokeChildAccess(childId: string, userId: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    schema(): Promise<string>;
    searchJournalNotes(childId: string, searchTerm: string): Promise<Array<JournalNote>>;
    shareChildWithUser(childId: string, userId: Principal): Promise<void>;
    startBreastfeedingSession(childId: string, side: Variant_left_right): Promise<void>;
    startTummyTimeSession(childId: string): Promise<void>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    toggleChildVisibility(childId: string): Promise<void>;
    updateHeightEntry(childId: string, heightId: string, newHeight: number, newTimestamp: bigint): Promise<void>;
    updateJournalNote(childId: string, noteId: string, newText: string, newColor: NoteColor | null): Promise<void>;
    updateSolidFoodEntry(childId: string, entryId: string, newFoodName: string, newCategory: Variant_grains_berries_eggs_fish_meat_fruits_vegetables, newColor: string, newReaction: Variant_unclear_liked_disliked, newNotes: string | null): Promise<void>;
    updateWeightEntry(childId: string, weightId: string, newWeight: number, newTimestamp: bigint): Promise<void>;
}
import type { ActiveTimerState as _ActiveTimerState, BreastfeedingSession as _BreastfeedingSession, Cell as _Cell, ChildProfileView as _ChildProfileView, ExternalBlob as _ExternalBlob, FeedingSession as _FeedingSession, JournalNote as _JournalNote, MilkPumpingSession as _MilkPumpingSession, NoteColor as _NoteColor, Result as _Result, SolidFoodEntry as _SolidFoodEntry, TummyTimeTimerState as _TummyTimeTimerState, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptChildInvite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptChildInvite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptChildInvite(arg0);
            return result;
        }
    }
    async addChild(arg0: string, arg1: bigint, arg2: ExternalBlob | null, arg3: boolean): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addChild(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addChild(arg0, arg1, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addFeedingSession(arg0: string, arg1: bigint, arg2: number, arg3: Variant_misinukas_mamosPienas, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFeedingSession(arg0, arg1, arg2, to_candid_variant_n10(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFeedingSession(arg0, arg1, arg2, to_candid_variant_n10(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async addHeightEntry(arg0: string, arg1: number, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHeightEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHeightEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addJournalNote(arg0: string, arg1: string, arg2: NoteColor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJournalNote(arg0, arg1, to_candid_NoteColor_n11(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJournalNote(arg0, arg1, to_candid_NoteColor_n11(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addManualBreastfeedingSession(arg0: string, arg1: bigint, arg2: bigint, arg3: Variant_left_right): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addManualBreastfeedingSession(arg0, arg1, arg2, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addManualBreastfeedingSession(arg0, arg1, arg2, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addMilkPumpingSession(arg0: string, arg1: bigint, arg2: number, arg3: Variant_both_left_right): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMilkPumpingSession(arg0, arg1, arg2, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMilkPumpingSession(arg0, arg1, arg2, to_candid_variant_n14(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addSolidFoodEntry(arg0: string, arg1: string, arg2: Variant_grains_berries_eggs_fish_meat_fruits_vegetables, arg3: string, arg4: Variant_unclear_liked_disliked, arg5: string | null, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSolidFoodEntry(arg0, arg1, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSolidFoodEntry(arg0, arg1, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async addWeightEntry(arg0: string, arg1: number, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeightEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeightEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateAgeInDays(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateAgeInDays(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateAgeInDays(arg0);
            return result;
        }
    }
    async completeBreastfeedingSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeBreastfeedingSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeBreastfeedingSession(arg0);
            return result;
        }
    }
    async completeTummyTimeSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTummyTimeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTummyTimeSession(arg0);
            return result;
        }
    }
    async deleteFeedingSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFeedingSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFeedingSession(arg0, arg1);
            return result;
        }
    }
    async deleteHeightEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHeightEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHeightEntry(arg0, arg1);
            return result;
        }
    }
    async deleteJournalNote(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalNote(arg0, arg1);
            return result;
        }
    }
    async deleteMilkPumpingSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMilkPumpingSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMilkPumpingSession(arg0, arg1);
            return result;
        }
    }
    async deleteSolidFoodEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSolidFoodEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSolidFoodEntry(arg0, arg1);
            return result;
        }
    }
    async deleteTummyTimeSession(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTummyTimeSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTummyTimeSession(arg0, arg1);
            return result;
        }
    }
    async deleteWeightEntry(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWeightEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWeightEntry(arg0, arg1);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async generateChildInviteLink(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateChildInviteLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateChildInviteLink(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getActiveBreastfeedingTimer(arg0: string): Promise<ActiveTimerState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveBreastfeedingTimer(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveBreastfeedingTimer(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveTummyTimeTimer(arg0: string): Promise<TummyTimeTimerState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTummyTimeTimer(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTummyTimeTimer(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicChildren(): Promise<Array<ChildProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicChildren();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicChildren();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getBreastfeedingSessionsForChild(arg0: string): Promise<Array<BreastfeedingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBreastfeedingSessionsForChild(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBreastfeedingSessionsForChild(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChild(arg0: string): Promise<ChildProfileView> {
        if (this.processError) {
            try {
                const result = await this.actor.getChild(arg0);
                return from_candid_ChildProfileView_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChild(arg0);
            return from_candid_ChildProfileView_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChildStatistics(arg0: string): Promise<{
        totalDiapers: bigint;
        totalBreastfeedingSessions: bigint;
        totalTummyTime: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildStatistics(arg0);
            return result;
        }
    }
    async getChildrenByParent(arg0: Principal): Promise<Array<ChildProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChildrenByParent(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChildrenByParent(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDiaperLogsForChild(arg0: string): Promise<Array<DiaperLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiaperLogsForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiaperLogsForChild(arg0);
            return result;
        }
    }
    async getFeedingSessionsForChild(arg0: string): Promise<Array<FeedingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeedingSessionsForChild(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeedingSessionsForChild(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeightEntriesForChild(arg0: string): Promise<Array<HeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeightEntriesForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeightEntriesForChild(arg0);
            return result;
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getJournalNotesForChild(arg0: string): Promise<Array<JournalNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalNotesForChild(arg0);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalNotesForChild(arg0);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMilkPumpingSessionsForChild(arg0: string): Promise<Array<MilkPumpingSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMilkPumpingSessionsForChild(arg0);
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMilkPumpingSessionsForChild(arg0);
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedChildren(): Promise<Array<ChildProfileView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedChildren();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedChildren();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSharedUsers(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSharedUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSharedUsers(arg0);
            return result;
        }
    }
    async getSolidFoodEntriesForChild(arg0: string): Promise<Array<SolidFoodEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSolidFoodEntriesForChild(arg0);
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSolidFoodEntriesForChild(arg0);
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSolidFoodStatistics(arg0: string): Promise<{
        thisWeek: bigint;
        thisYear: bigint;
        thisMonth: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSolidFoodStatistics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSolidFoodStatistics(arg0);
            return result;
        }
    }
    async getSolidFoodStatisticsByCategory(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        grains: bigint;
        berries: bigint;
        eggs: bigint;
        fish: bigint;
        meat: bigint;
        fruits: bigint;
        vegetables: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSolidFoodStatisticsByCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSolidFoodStatisticsByCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async getTummyTimeSessionsForChild(arg0: string): Promise<Array<TummyTimeSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTummyTimeSessionsForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTummyTimeSessionsForChild(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeightEntriesForChild(arg0: string): Promise<Array<WeightEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeightEntriesForChild(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeightEntriesForChild(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logDiaperChange(arg0: string, arg1: boolean, arg2: boolean, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logDiaperChange(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logDiaperChange(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async pauseBreastfeedingTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseBreastfeedingTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseBreastfeedingTimer(arg0);
            return result;
        }
    }
    async pauseTummyTimeTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pauseTummyTimeTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pauseTummyTimeTimer(arg0);
            return result;
        }
    }
    async regenerateChildPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.regenerateChildPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.regenerateChildPhoto(arg0);
            return result;
        }
    }
    async resumeBreastfeedingTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeBreastfeedingTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeBreastfeedingTimer(arg0);
            return result;
        }
    }
    async resumeTummyTimeTimer(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resumeTummyTimeTimer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resumeTummyTimeTimer(arg0);
            return result;
        }
    }
    async revokeChildAccess(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeChildAccess(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeChildAccess(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchJournalNotes(arg0: string, arg1: string): Promise<Array<JournalNote>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJournalNotes(arg0, arg1);
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJournalNotes(arg0, arg1);
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async shareChildWithUser(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.shareChildWithUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shareChildWithUser(arg0, arg1);
            return result;
        }
    }
    async startBreastfeedingSession(arg0: string, arg1: Variant_left_right): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startBreastfeedingSession(arg0, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startBreastfeedingSession(arg0, to_candid_variant_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async startTummyTimeSession(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTummyTimeSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTummyTimeSession(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleChildVisibility(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleChildVisibility(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleChildVisibility(arg0);
            return result;
        }
    }
    async updateHeightEntry(arg0: string, arg1: string, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHeightEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHeightEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateJournalNote(arg0: string, arg1: string, arg2: string, arg3: NoteColor | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalNote(arg0, arg1, arg2, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalNote(arg0, arg1, arg2, to_candid_opt_n66(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateSolidFoodEntry(arg0: string, arg1: string, arg2: string, arg3: Variant_grains_berries_eggs_fish_meat_fruits_vegetables, arg4: string, arg5: Variant_unclear_liked_disliked, arg6: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSolidFoodEntry(arg0, arg1, arg2, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSolidFoodEntry(arg0, arg1, arg2, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_variant_n16(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateWeightEntry(arg0: string, arg1: string, arg2: number, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeightEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeightEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_ActiveTimerState_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActiveTimerState): ActiveTimerState {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_BreastfeedingSession_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BreastfeedingSession): BreastfeedingSession {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ChildProfileView_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ChildProfileView): Promise<ChildProfileView> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FeedingSession_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedingSession): FeedingSession {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_JournalNote_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JournalNote): JournalNote {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_MilkPumpingSession_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MilkPumpingSession): MilkPumpingSession {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_NoteColor_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoteColor): NoteColor {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_SolidFoodEntry_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SolidFoodEntry): SolidFoodEntry {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_TummyTimeTimerState_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TummyTimeTimerState): TummyTimeTimerState {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ActiveTimerState]): ActiveTimerState | null {
    return value.length === 0 ? null : from_candid_ActiveTimerState_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TummyTimeTimerState]): TummyTimeTimerState | null {
    return value.length === 0 ? null : from_candid_TummyTimeTimerState_n34(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n22(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n26(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    pausedAt: [] | [bigint];
    userId: Principal;
    isPaused: boolean;
    side: {
        left: null;
    } | {
        right: null;
    };
    totalPausedDuration: bigint;
    childId: string;
}): {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    side: Variant_left_right;
    totalPausedDuration: bigint;
    childId: string;
} {
    return {
        startTime: value.startTime,
        pausedAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.pausedAt)),
        userId: value.userId,
        isPaused: value.isPaused,
        side: from_candid_variant_n32(_uploadFile, _downloadFile, value.side),
        totalPausedDuration: value.totalPausedDuration,
        childId: value.childId
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    pausedAt: [] | [bigint];
    userId: Principal;
    isPaused: boolean;
    totalPausedDuration: bigint;
    childId: string;
}): {
    startTime: bigint;
    pausedAt?: bigint;
    userId: Principal;
    isPaused: boolean;
    totalPausedDuration: bigint;
    childId: string;
} {
    return {
        startTime: value.startTime,
        pausedAt: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.pausedAt)),
        userId: value.userId,
        isPaused: value.isPaused,
        totalPausedDuration: value.totalPausedDuration,
        childId: value.childId
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    birthDate: bigint;
    name: string;
    sharedWith: Array<Principal>;
    isPublic: boolean;
    photo: [] | [_ExternalBlob];
    parent: Principal;
}): Promise<{
    id: string;
    birthDate: bigint;
    name: string;
    sharedWith: Array<Principal>;
    isPublic: boolean;
    photo?: ExternalBlob;
    parent: Principal;
}> {
    return {
        id: value.id,
        birthDate: value.birthDate,
        name: value.name,
        sharedWith: value.sharedWith,
        isPublic: value.isPublic,
        photo: record_opt_to_undefined(await from_candid_opt_n39(_uploadFile, _downloadFile, value.photo)),
        parent: value.parent
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: bigint;
    duration: bigint;
    side: {
        left: null;
    } | {
        right: null;
    };
    childId: string;
}): {
    startTime: bigint;
    duration: bigint;
    side: Variant_left_right;
    childId: string;
} {
    return {
        startTime: value.startTime,
        duration: value.duration,
        side: from_candid_variant_n32(_uploadFile, _downloadFile, value.side),
        childId: value.childId
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: string;
    feedingType: {
        misinukas: null;
    } | {
        mamosPienas: null;
    };
    childId: string;
    timestamp: bigint;
    sessionId: string;
    mlAmount: number;
}): {
    color: string;
    feedingType: Variant_misinukas_mamosPienas;
    childId: string;
    timestamp: bigint;
    sessionId: string;
    mlAmount: number;
} {
    return {
        color: value.color,
        feedingType: from_candid_variant_n50(_uploadFile, _downloadFile, value.feedingType),
        childId: value.childId,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        mlAmount: value.mlAmount
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    createdAt: bigint;
    color: _NoteColor;
    text: string;
    childId: string;
    updatedAt: bigint;
}): {
    createdAt: bigint;
    color: NoteColor;
    text: string;
    childId: string;
    updatedAt: bigint;
} {
    return {
        createdAt: value.createdAt,
        color: from_candid_NoteColor_n54(_uploadFile, _downloadFile, value.color),
        text: value.text,
        childId: value.childId,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    side: {
        both: null;
    } | {
        left: null;
    } | {
        right: null;
    };
    childId: string;
    timestamp: bigint;
    sessionId: string;
    mlAmount: number;
}): {
    side: Variant_both_left_right;
    childId: string;
    timestamp: bigint;
    sessionId: string;
    mlAmount: number;
} {
    return {
        side: from_candid_variant_n59(_uploadFile, _downloadFile, value.side),
        childId: value.childId,
        timestamp: value.timestamp,
        sessionId: value.sessionId,
        mlAmount: value.mlAmount
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: string;
    childId: string;
    entryId: string;
    notes: [] | [string];
    timestamp: bigint;
    category: {
        grains: null;
    } | {
        berries: null;
    } | {
        eggs: null;
    } | {
        fish: null;
    } | {
        meat: null;
    } | {
        fruits: null;
    } | {
        vegetables: null;
    };
    reaction: {
        unclear: null;
    } | {
        liked: null;
    } | {
        disliked: null;
    };
    foodName: string;
}): {
    color: string;
    childId: string;
    entryId: string;
    notes?: string;
    timestamp: bigint;
    category: Variant_grains_berries_eggs_fish_meat_fruits_vegetables;
    reaction: Variant_unclear_liked_disliked;
    foodName: string;
} {
    return {
        color: value.color,
        childId: value.childId,
        entryId: value.entryId,
        notes: record_opt_to_undefined(from_candid_opt_n63(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        category: from_candid_variant_n64(_uploadFile, _downloadFile, value.category),
        reaction: from_candid_variant_n65(_uploadFile, _downloadFile, value.reaction),
        foodName: value.foodName
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    left: null;
} | {
    right: null;
}): Variant_left_right {
    return "left" in value ? Variant_left_right.left : "right" in value ? Variant_left_right.right : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    misinukas: null;
} | {
    mamosPienas: null;
}): Variant_misinukas_mamosPienas {
    return "misinukas" in value ? Variant_misinukas_mamosPienas.misinukas : "mamosPienas" in value ? Variant_misinukas_mamosPienas.mamosPienas : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blue: null;
} | {
    pink: null;
} | {
    purple: null;
} | {
    green: null;
} | {
    yellow: null;
}): NoteColor {
    return "blue" in value ? NoteColor.blue : "pink" in value ? NoteColor.pink : "purple" in value ? NoteColor.purple : "green" in value ? NoteColor.green : "yellow" in value ? NoteColor.yellow : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    left: null;
} | {
    right: null;
}): Variant_both_left_right {
    return "both" in value ? Variant_both_left_right.both : "left" in value ? Variant_both_left_right.left : "right" in value ? Variant_both_left_right.right : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grains: null;
} | {
    berries: null;
} | {
    eggs: null;
} | {
    fish: null;
} | {
    meat: null;
} | {
    fruits: null;
} | {
    vegetables: null;
}): Variant_grains_berries_eggs_fish_meat_fruits_vegetables {
    return "grains" in value ? Variant_grains_berries_eggs_fish_meat_fruits_vegetables.grains : "berries" in value ? Variant_grains_berries_eggs_fish_meat_fruits_vegetables.berries : "eggs" in value ? Variant_grains_berries_eggs_fish_meat_fruits_vegetables.eggs : "fish" in value ? Variant_grains_berries_eggs_fish_meat_fruits_vegetables.fish : "meat" in value ? Variant_grains_berries_eggs_fish_meat_fruits_vegetables.meat : "fruits" in value ? Variant_grains_berries_eggs_fish_meat_fruits_vegetables.fruits : "vegetables" in value ? Variant_grains_berries_eggs_fish_meat_fruits_vegetables.vegetables : value;
}
function from_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    unclear: null;
} | {
    liked: null;
} | {
    disliked: null;
}): Variant_unclear_liked_disliked {
    return "unclear" in value ? Variant_unclear_liked_disliked.unclear : "liked" in value ? Variant_unclear_liked_disliked.liked : "disliked" in value ? Variant_unclear_liked_disliked.disliked : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n24(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ChildProfileView>): Promise<Array<ChildProfileView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ChildProfileView_n37(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BreastfeedingSession>): Array<BreastfeedingSession> {
    return value.map((x)=>from_candid_BreastfeedingSession_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FeedingSession>): Array<FeedingSession> {
    return value.map((x)=>from_candid_FeedingSession_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JournalNote>): Array<JournalNote> {
    return value.map((x)=>from_candid_JournalNote_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MilkPumpingSession>): Array<MilkPumpingSession> {
    return value.map((x)=>from_candid_MilkPumpingSession_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SolidFoodEntry>): Array<SolidFoodEntry> {
    return value.map((x)=>from_candid_SolidFoodEntry_n61(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_NoteColor_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteColor): _NoteColor {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteColor | null): [] | [_NoteColor] {
    return value === null ? candid_none() : candid_some(to_candid_NoteColor_n11(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_misinukas_mamosPienas): {
    misinukas: null;
} | {
    mamosPienas: null;
} {
    return value == Variant_misinukas_mamosPienas.misinukas ? {
        misinukas: null
    } : value == Variant_misinukas_mamosPienas.mamosPienas ? {
        mamosPienas: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteColor): {
    blue: null;
} | {
    pink: null;
} | {
    purple: null;
} | {
    green: null;
} | {
    yellow: null;
} {
    return value == NoteColor.blue ? {
        blue: null
    } : value == NoteColor.pink ? {
        pink: null
    } : value == NoteColor.purple ? {
        purple: null
    } : value == NoteColor.green ? {
        green: null
    } : value == NoteColor.yellow ? {
        yellow: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_left_right): {
    left: null;
} | {
    right: null;
} {
    return value == Variant_left_right.left ? {
        left: null
    } : value == Variant_left_right.right ? {
        right: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_both_left_right): {
    both: null;
} | {
    left: null;
} | {
    right: null;
} {
    return value == Variant_both_left_right.both ? {
        both: null
    } : value == Variant_both_left_right.left ? {
        left: null
    } : value == Variant_both_left_right.right ? {
        right: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_grains_berries_eggs_fish_meat_fruits_vegetables): {
    grains: null;
} | {
    berries: null;
} | {
    eggs: null;
} | {
    fish: null;
} | {
    meat: null;
} | {
    fruits: null;
} | {
    vegetables: null;
} {
    return value == Variant_grains_berries_eggs_fish_meat_fruits_vegetables.grains ? {
        grains: null
    } : value == Variant_grains_berries_eggs_fish_meat_fruits_vegetables.berries ? {
        berries: null
    } : value == Variant_grains_berries_eggs_fish_meat_fruits_vegetables.eggs ? {
        eggs: null
    } : value == Variant_grains_berries_eggs_fish_meat_fruits_vegetables.fish ? {
        fish: null
    } : value == Variant_grains_berries_eggs_fish_meat_fruits_vegetables.meat ? {
        meat: null
    } : value == Variant_grains_berries_eggs_fish_meat_fruits_vegetables.fruits ? {
        fruits: null
    } : value == Variant_grains_berries_eggs_fish_meat_fruits_vegetables.vegetables ? {
        vegetables: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_unclear_liked_disliked): {
    unclear: null;
} | {
    liked: null;
} | {
    disliked: null;
} {
    return value == Variant_unclear_liked_disliked.unclear ? {
        unclear: null
    } : value == Variant_unclear_liked_disliked.liked ? {
        liked: null
    } : value == Variant_unclear_liked_disliked.disliked ? {
        disliked: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
